In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn.cluster import KMeans as km
import sklearn.utils as skut
import gmplot as gm
import geocoder

In [2]:
data=pd.read_csv("FinalGeoDataSetWithCrime.csv")

In [3]:
data

           District         Timestamp   Latitude  Longitude           Crime
0           CENTRAL  03-02-2019 22:20  28.645000  77.245003         Robbery
1           CENTRAL  04-02-2019 03:00  28.643760  77.231360          Murder
2           CENTRAL  03-02-2019 21:00  28.690560  77.041820          Murder
3           CENTRAL  03-02-2019 22:00  28.645000  77.245003      Kidnapping
4           CENTRAL  03-02-2019 22:00  28.643220  77.217530      Kidnapping
5            DWARKA  03-02-2019 20:38  28.589951  77.040070  Sexual Offense
6            DWARKA  03-02-2019 23:00  28.590230  77.070320      Kidnapping
7            DWARKA  03-02-2019 20:24  28.589951  77.040070      Kidnapping
8            DWARKA  03-02-2019 20:38  28.625380  76.966950  Sexual Offense
9            DWARKA  03-02-2019 20:24  28.589951  77.040070           Drugs
10             EAST  03-02-2019 21:51  28.639999  77.290001  Sexual Offense
11             EAST  04-02-2019 02:23  28.593600  77.325150          Murder
12             EAST  04-02-2019 00:15  28.605920  77.299470  Sexual Offense
13             EAST  03-02-2019 18:00  28.639999  77.290001      Kidnapping
14             EAST  04-02-2019 01:00  28.616420  77.316960           Drugs
15             EAST  04-02-2019 07:19  28.618880  77.315490         Robbery
16             EAST  03-02-2019 17:40  28.632530  77.298850          Murder
17             EAST  03-02-2019 23:36  28.639999  77.290001  Sexual Offense
18             EAST  04-02-2019 01:00  28.639999  77.290001           Drugs
19             EAST  04-02-2019 02:54  28.604040  77.379677           Drugs
20             EAST  03-02-2019 22:30  28.644690  77.343930      Kidnapping
21             EAST  03-02-2019 22:30  28.740780  77.768900  Sexual Offense
22        NEW DELHI  03-02-2019 23:59  29.099020  77.256409         Robbery
23        NEW DELHI  03-02-2019 23:58  28.633850  77.200260         Robbery
24            NORTH  04-02-2019 07:30  28.676313  77.224976         Robbery
25            NORTH  04-02-2019 00:05  28.676313  77.224976      Kidnapping
26       NORTH EAST  03-02-2019 19:00  28.696290  77.311810         Robbery
27       NORTH EAST  04-02-2019 00:30  28.701500  77.317070         Robbery
28       NORTH EAST  04-02-2019 02:58  28.688430  77.299480      Kidnapping
29       NORTH EAST  03-02-2019 19:30  28.694840  77.348210          Murder
..              ...               ...        ...        ...             ...
349  OUTER DISTRICT  09-02-2019 13:18  28.687420  77.096070      Kidnapping
350  OUTER DISTRICT  09-02-2019 02:26  28.698200  77.071970  Sexual Offense
351  OUTER DISTRICT  09-02-2019 11:00  28.689560  77.096480  Sexual Offense
352  OUTER DISTRICT  08-02-2019 23:44  28.634109  77.216911      Kidnapping
353  OUTER DISTRICT  08-02-2019 21:00  28.652920  77.041220  Sexual Offense
354  OUTER DISTRICT  08-02-2019 20:01  28.687420  77.096070         Robbery
355  OUTER DISTRICT  08-02-2019 20:19  28.634109  77.216911  Sexual Offense
356  OUTER DISTRICT  08-02-2019 23:00  28.634109  77.216911      Kidnapping
357  OUTER DISTRICT  09-02-2019 23:30  28.634109  77.216911      Kidnapping
358     OUTER NORTH  08-02-2019 23:45  28.676313  77.224976         Robbery
359     OUTER NORTH  08-02-2019 21:59  28.694860  77.189160           Drugs
360     OUTER NORTH  08-02-2019 21:50  28.676313  77.224976           Drugs
361          ROHINI  08-02-2019 21:11  28.876909  76.911949      Kidnapping
362          ROHINI  08-02-2019 23:50  28.705500  77.281810  Sexual Offense
363          ROHINI  08-02-2019 21:30  28.700150  77.045700          Murder
364       SHAHDAR A  08-02-2019 22:27  28.689590  77.278023  Sexual Offense
365       SHAHDAR A  08-02-2019 21:42  28.350273  78.002945      Kidnapping
366       SHAHDAR A  08-02-2019 17:10  28.678160  77.408607  Sexual Offense
367        SHAHDARA  08-02-2019 16:50  28.696930  77.421150           Drugs
368        SHAHDARA  09-02-2019 00:40  29.470289  77.707588      Kidnapping
369           SOUTH  08-02-2019 16:20  28.706400  77.282610         Robbery
370           SOUTH  09-02-2019 02:19  28.554899  77.191902         Robbery
371           SOUTH  09-02-2019 00:00  28.533500  77.199340      Kidnapping
372      SOUTH WEST  08-02-2019 21:35  28.648720  77.179340          Murder
373      SOUTH WEST  08-02-2019 18:00  28.609550  77.139671      Kidnapping
374     SOUTH- EAST  08-02-2019 16:52  22.716221  75.865120      Kidnapping
375     SOUTH- EAST  08-02-2019 22:00  28.532620  77.253470  Sexual Offense
376     SOUTH- EAST  08-02-2019 05:00  28.725838  77.149414  Sexual Offense
377     SOUTH- EAST  08-02-2019 21:20  28.639999  77.290001  Sexual Offense
378            WEST  08-02-2019 22:04  28.696400  77.127098         Robbery

[379 rows x 5 columns]

In [4]:
lis=['District']
for c in lis:
    data.drop(c, axis=1, inplace=True)

In [5]:
def f(s):
    s1=s[11:13]
    s2=s[14:]
    s3=s1+s2
    return int(s3)
data['newCol']=data.Timestamp.apply(f)
del data["Timestamp"]

In [6]:
data

      Latitude  Longitude           Crime  newCol
0    28.645000  77.245003         Robbery    2220
1    28.643760  77.231360          Murder     300
2    28.690560  77.041820          Murder    2100
3    28.645000  77.245003      Kidnapping    2200
4    28.643220  77.217530      Kidnapping    2200
5    28.589951  77.040070  Sexual Offense    2038
6    28.590230  77.070320      Kidnapping    2300
7    28.589951  77.040070      Kidnapping    2024
8    28.625380  76.966950  Sexual Offense    2038
9    28.589951  77.040070           Drugs    2024
10   28.639999  77.290001  Sexual Offense    2151
11   28.593600  77.325150          Murder     223
12   28.605920  77.299470  Sexual Offense      15
13   28.639999  77.290001      Kidnapping    1800
14   28.616420  77.316960           Drugs     100
15   28.618880  77.315490         Robbery     719
16   28.632530  77.298850          Murder    1740
17   28.639999  77.290001  Sexual Offense    2336
18   28.639999  77.290001           Drugs     100
19   28.604040  77.379677           Drugs     254
20   28.644690  77.343930      Kidnapping    2230
21   28.740780  77.768900  Sexual Offense    2230
22   29.099020  77.256409         Robbery    2359
23   28.633850  77.200260         Robbery    2358
24   28.676313  77.224976         Robbery     730
25   28.676313  77.224976      Kidnapping       5
26   28.696290  77.311810         Robbery    1900
27   28.701500  77.317070         Robbery      30
28   28.688430  77.299480      Kidnapping     258
29   28.694840  77.348210          Murder    1930
..         ...        ...             ...     ...
349  28.687420  77.096070      Kidnapping    1318
350  28.698200  77.071970  Sexual Offense     226
351  28.689560  77.096480  Sexual Offense    1100
352  28.634109  77.216911      Kidnapping    2344
353  28.652920  77.041220  Sexual Offense    2100
354  28.687420  77.096070         Robbery    2001
355  28.634109  77.216911  Sexual Offense    2019
356  28.634109  77.216911      Kidnapping    2300
357  28.634109  77.216911      Kidnapping    2330
358  28.676313  77.224976         Robbery    2345
359  28.694860  77.189160           Drugs    2159
360  28.676313  77.224976           Drugs    2150
361  28.876909  76.911949      Kidnapping    2111
362  28.705500  77.281810  Sexual Offense    2350
363  28.700150  77.045700          Murder    2130
364  28.689590  77.278023  Sexual Offense    2227
365  28.350273  78.002945      Kidnapping    2142
366  28.678160  77.408607  Sexual Offense    1710
367  28.696930  77.421150           Drugs    1650
368  29.470289  77.707588      Kidnapping      40
369  28.706400  77.282610         Robbery    1620
370  28.554899  77.191902         Robbery     219
371  28.533500  77.199340      Kidnapping       0
372  28.648720  77.179340          Murder    2135
373  28.609550  77.139671      Kidnapping    1800
374  22.716221  75.865120      Kidnapping    1652
375  28.532620  77.253470  Sexual Offense    2200
376  28.725838  77.149414  Sexual Offense     500
377  28.639999  77.290001  Sexual Offense    2120
378  28.696400  77.127098         Robbery    2204

[379 rows x 4 columns]

In [7]:
day = pd.DataFrame(columns=['Latitude','Longitude','newCol'])
day = day.fillna(0) # with 0s rather than NaNs
day

Empty DataFrame
Columns: [Latitude, Longitude, newCol]
Index: []

In [8]:
night = pd.DataFrame(columns=['Latitude','Longitude','newCol'])
night = night.fillna(0) 
night

Empty DataFrame
Columns: [Latitude, Longitude, newCol]
Index: []

In [9]:
day=data.loc[(data['newCol'] >= 600) & (data['newCol'] <= 2000)] 
night=data.loc[((data['newCol'] >=0) & (data['newCol'] <= 559)) | ((data['newCol'] >= 2001) & (data['newCol'] < 2400))]

In [10]:
day=day.drop('newCol', axis=1)
day

      Latitude  Longitude           Crime
13   28.639999  77.290001      Kidnapping
15   28.618880  77.315490         Robbery
16   28.632530  77.298850          Murder
24   28.676313  77.224976         Robbery
26   28.696290  77.311810         Robbery
29   28.694840  77.348210          Murder
30   28.693600  77.307297         Robbery
36   28.705350  77.313530      Kidnapping
37   28.690770  77.273630  Sexual Offense
40   28.705350  77.313530      Kidnapping
51   28.707540  77.177360      Kidnapping
66   25.678825  85.612419          Murder
68   28.612030  77.314110          Murder
70   25.678825  85.612419          Murder
71   28.612030  77.314110          Murder
72   28.612030  77.314110          Murder
73   25.678825  85.612419          Murder
75   28.701220  77.084520      Kidnapping
78   28.667540  77.314750         Robbery
84   28.554899  77.191902           Drugs
96   28.634109  77.216911           Drugs
97   28.609550  77.139671  Sexual Offense
99   28.609550  77.139671           Drugs
100  28.609550  77.139671  Sexual Offense
102  28.661850  77.140820         Robbery
103  28.661250  77.139720         Robbery
104  28.656390  77.136000         Robbery
114  28.622800  77.288200      Kidnapping
115  28.609550  77.139671          Murder
116  31.110476  76.154762         Robbery
..         ...        ...             ...
299  28.706640  77.267170  Sexual Offense
300  28.678160  77.408607      Kidnapping
301  28.758369  77.283928      Kidnapping
302  28.515020  77.178470  Sexual Offense
304  28.523390  77.177290          Murder
307  28.624990  77.283690           Drugs
308  30.935390  75.875280  Sexual Offense
310  28.563750  77.217400      Kidnapping
314  28.647970  77.136470           Drugs
315  28.715430  77.278350          Murder
316  28.922140  77.637062      Kidnapping
320  28.553221  77.337502          Murder
321  28.639999  77.290001          Murder
322  28.614720  77.289190          Murder
323  28.625470  77.316220      Kidnapping
324  28.702710  77.314520  Sexual Offense
325  28.672780  77.255870          Murder
326  28.693600  77.307297           Drugs
327  28.693600  77.307297  Sexual Offense
331  28.693600  77.307297      Kidnapping
332  28.739020  77.166910         Robbery
342  28.689560  77.096480           Drugs
343  28.634109  77.216911           Drugs
349  28.687420  77.096070      Kidnapping
351  28.689560  77.096480  Sexual Offense
366  28.678160  77.408607  Sexual Offense
367  28.696930  77.421150           Drugs
369  28.706400  77.282610         Robbery
373  28.609550  77.139671      Kidnapping
374  22.716221  75.865120      Kidnapping

[132 rows x 3 columns]

In [11]:
night=night.drop('newCol', axis=1)
night

      Latitude  Longitude           Crime
0    28.645000  77.245003         Robbery
1    28.643760  77.231360          Murder
2    28.690560  77.041820          Murder
3    28.645000  77.245003      Kidnapping
4    28.643220  77.217530      Kidnapping
5    28.589951  77.040070  Sexual Offense
6    28.590230  77.070320      Kidnapping
7    28.589951  77.040070      Kidnapping
8    28.625380  76.966950  Sexual Offense
9    28.589951  77.040070           Drugs
10   28.639999  77.290001  Sexual Offense
11   28.593600  77.325150          Murder
12   28.605920  77.299470  Sexual Offense
14   28.616420  77.316960           Drugs
17   28.639999  77.290001  Sexual Offense
18   28.639999  77.290001           Drugs
19   28.604040  77.379677           Drugs
20   28.644690  77.343930      Kidnapping
21   28.740780  77.768900  Sexual Offense
22   29.099020  77.256409         Robbery
23   28.633850  77.200260         Robbery
25   28.676313  77.224976      Kidnapping
27   28.701500  77.317070         Robbery
28   28.688430  77.299480      Kidnapping
31   28.691180  77.289830         Robbery
32   28.692230  77.301270         Robbery
33   28.692470  77.288260         Robbery
34   27.948139  80.777771      Kidnapping
35   28.648940  77.281160         Robbery
38   28.672760  77.275140      Kidnapping
..         ...        ...             ...
340  28.676313  77.224976  Sexual Offense
341  28.691560  77.092570         Robbery
344  28.634109  77.216911      Kidnapping
345  28.634109  77.216911           Drugs
346  28.634109  77.216911           Drugs
347  28.652920  77.041220  Sexual Offense
348  28.634109  77.216911           Drugs
350  28.698200  77.071970  Sexual Offense
352  28.634109  77.216911      Kidnapping
353  28.652920  77.041220  Sexual Offense
354  28.687420  77.096070         Robbery
355  28.634109  77.216911  Sexual Offense
356  28.634109  77.216911      Kidnapping
357  28.634109  77.216911      Kidnapping
358  28.676313  77.224976         Robbery
359  28.694860  77.189160           Drugs
360  28.676313  77.224976           Drugs
361  28.876909  76.911949      Kidnapping
362  28.705500  77.281810  Sexual Offense
363  28.700150  77.045700          Murder
364  28.689590  77.278023  Sexual Offense
365  28.350273  78.002945      Kidnapping
368  29.470289  77.707588      Kidnapping
370  28.554899  77.191902         Robbery
371  28.533500  77.199340      Kidnapping
372  28.648720  77.179340          Murder
375  28.532620  77.253470  Sexual Offense
376  28.725838  77.149414  Sexual Offense
377  28.639999  77.290001  Sexual Offense
378  28.696400  77.127098         Robbery

[247 rows x 3 columns]

In [12]:
xs1=day[day.Latitude< 28.412782]
xs2=day[day.Latitude> 28.88]
xs3=day[day.Longitude< 76.838084]
xs4=day[day.Longitude> 77.323460]
frames1 = [xs1, xs2, xs3,xs4];
xsFinal1 = pd.concat(frames1)

In [13]:
xs11=night[night.Latitude< 28.412782]
xs22=night[night.Latitude> 28.88]
xs33=night[night.Longitude< 76.838084]
xs44=night[night.Longitude> 77.323460]
frames2 = [xs11, xs22, xs33,xs44];
xsFinal2 = pd.concat(frames2)

In [14]:
#xsFinal.to_csv("Xfinal.csv")

In [15]:
for i in xsFinal1.index:
    if(i in day.index):
        day.drop(i,inplace=True)

In [16]:
for i in xsFinal2.index:
    if(i in night.index):
        night.drop(i,inplace=True)

In [17]:
#data

In [18]:
day.reset_index(drop=True,inplace=True)
night.reset_index(drop=True,inplace=True)

In [19]:
data['Latitude'].size

379

In [20]:
day=skut.shuffle(day)
night=skut.shuffle(night)

In [21]:
daydata1=day.copy()
nightdata1=night.copy()

In [22]:
day=day.drop('Crime', axis=1)
night=night.drop('Crime', axis=1)

In [23]:
del_index=night[night['Longitude']==76.91194916].index

In [24]:
night.loc[del_index]

      Latitude  Longitude
209  28.876909  76.911949

In [25]:
night=night.drop(del_index)
nightdata1=nightdata1.drop(del_index)

In [26]:
data.describe()

         Latitude   Longitude       newCol
count  379.000000  379.000000   379.000000
mean    28.533016   77.410762  1717.928760
std      1.028370    1.230976   713.103978
min     12.977110   75.532768     0.000000
25%     28.613375   77.138071  1500.000000
50%     28.671370   77.216911  2017.000000
75%     28.694225   77.289915  2223.500000
max     31.110476   86.073158  2359.000000

In [27]:
data['Latitude'].mean()

28.533015961240107

In [28]:
data['Longitude'].mean()

77.4107618239578

In [29]:
# data.to_csv("TrainingData.csv")
# data1.to_csv("CrimeTrainingData.csv")
day.to_csv("Day.csv")
night.to_csv("Night.csv")
daydata1.to_csv("DayCrime.csv")
nightdata1.to_csv("NightCrime.csv")

In [30]:
kmeans = km(n_clusters=18).fit(day)
kmeans1 = km(n_clusters=18).fit(night)

In [31]:
prediction=kmeans.predict(day)

In [32]:
centers=kmeans.cluster_centers_

In [33]:
centers

array([[28.69771496, 77.10487976],
       [28.68254232, 77.27527617],
       [28.46642   , 77.16719   ],
       [28.60955048, 77.13967133],
       [28.61622667, 77.31529333],
       [28.68253   , 76.91402   ],
       [28.69415911, 77.308856  ],
       [28.54857109, 77.18703378],
       [28.73305924, 77.16528135],
       [28.6803882 , 77.22331101],
       [28.65585   , 77.140896  ],
       [28.69296333, 77.07323667],
       [28.62751978, 77.28688224],
       [28.60361   , 77.04174   ],
       [28.50608   , 77.2537    ],
       [28.63984483, 77.21918779],
       [28.71577368, 77.27135224],
       [28.54071   , 77.13056   ]])

In [34]:
prediction

array([11,  6,  8,  3, 13,  7,  2, 12, 10,  4, 10, 15,  3,  4, 15, 13,  3,
        0, 14,  7,  9, 15,  3,  3, 12,  1, 16, 12, 10,  0, 16,  9,  9, 12,
        8, 12,  9,  3,  0,  7, 10, 16,  8,  6, 10,  6,  3,  1,  1, 16, 16,
       11, 11,  3,  8, 12,  7,  1,  6,  2, 12,  4, 11,  9,  9,  3,  0,  6,
        1,  3,  6,  4,  3,  0,  1,  5,  6, 16,  6, 12,  1,  4,  7,  0, 12,
       16,  1,  4,  7, 17,  6,  6, 11,  0,  9,  8,  6,  6, 16,  9,  8, 11,
       15, 15, 15,  7,  1,  6,  9,  3,  0,  6])

In [35]:
center_count=[]

In [36]:
for i in range(18):
    center_count.append(list(prediction).count(i))

In [37]:
center_count

[8, 9, 2, 12, 6, 1, 14, 7, 6, 9, 5, 6, 9, 2, 1, 6, 8, 1]

In [38]:
max_value=max(center_count)

In [39]:
min_value=min(center_count)

In [40]:
avg_value=(max_value+min_value)/3

In [41]:
range1=int(min_value+avg_value)

In [42]:
range1

6

In [43]:
range2=int(max_value-avg_value)

In [44]:
range2

9

In [45]:
#color_list=['cornflowerblue', 'red', 'green', 'yellow', 'brown', 'black', 'aqua', 'darkgray', 'gold', 'ghostwhite', 'hotpink', 'mistyrose', 'orange', 'purple', 'silver', 'lime', 'salmon', 'steelblue']

In [46]:
color_list=['red', 'yellow', 'green']

In [47]:
g = geocoder.bing("Delhi, India", key='Av3MzjFGfdPT198iOOm1o5cUm9SohZKyKX_4ioh0IPW8xj4Uut_HOFxz2hbOAKyV')

In [48]:
gmap1 = gm.GoogleMapPlotter(g.lat, g.lng, 12)
gmap1.scatter(list(data['Latitude']), list(data['Longitude']), '# FF0000', size = 100, marker = False)

In [49]:
j=0
for i in centers:
    if center_count[j] in range(min_value, range1):
        gmap1.marker(i[0], i[1], color_list[2])
    elif center_count[j] in range(range2, max_value+1):
        gmap1.marker(i[0], i[1], color_list[0])
    else:
        gmap1.marker(i[0], i[1], color_list[1])
    j=j+1

In [50]:
gmap1.draw("cluster.html")

In [51]:
g.bbox

{'northeast': [28.71649932861328, 77.32664489746094],
 'southwest': [28.50888442993164, 77.07470703125]}

In [52]:
gmap2 = gm.GoogleMapPlotter(g.lat, g.lng, 12)
gmap2.scatter(list(data['Latitude']), list(data['Longitude']), '# FF0000', size = 100, marker = False)

In [53]:
gmap2.marker(28.715712, 77.323460, 'cornflowerblue')
gmap2.marker(28.412782, 77.200218, 'red')
gmap2.marker(28.88, 77.07470703125, 'green')
gmap2.marker(28.577869, 76.838084, 'yellow')

In [54]:
gmap2.draw("abcdef.html")

In [55]:
import pickle

In [56]:
# filename="model1.sav"
# pickle.dump(kmeans, open(filename, 'wb'))
filename="modelday.sav"
pickle.dump(kmeans, open(filename, 'wb'))

In [57]:
filename="modelnight.sav"
pickle.dump(kmeans1, open(filename, 'wb'))