In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn.cluster import KMeans as km
import sklearn.utils as skut
import gmplot as gm
import geocoder

In [2]:
data=pd.read_csv("Final.csv")

In [3]:
data

,District,Crime,Timestamp,Latitude,Longitude
0,CENTRAL,356/379/411 IPC 1860,03-02-2019 22:20,28.645000,77.245003
1,CENTRAL,323/341/506 IPC 1860,04-02-2019 03:00,28.643760,77.231360
2,CENTRAL,283/290 IPC 1860,03-02-2019 21:00,28.690560,77.041820
3,CENTRAL,93/97 DELHI POLICE ACT 1978,03-02-2019 22:00,28.645000,77.245003
4,CENTRAL,93/97 DELHI POLICE ACT 1978,03-02-2019 22:00,28.643220,77.217530
5,DWARKA,"40(b) DELHI EXCISE ACT, 2009",03-02-2019 20:38,28.589951,77.040070
6,DWARKA,93/97 DELHI POLICE ACT 1978,03-02-2019 23:00,28.590220,77.070330
7,DWARKA,"40(b) DELHI EXCISE ACT, 2009",03-02-2019 20:24,28.589951,77.040070
8,DWARKA,"40(b) DELHI EXCISE ACT, 2009",03-02-2019 20:38,28.625380,76.966950
9,DWARKA,"40(b) DELHI EXCISE ACT, 2009",03-02-2019 20:24,28.589951,77.040070
10,EAST,"33 DELHI EXCISE ACT, 2010",03-02-2019 21:51,28.639999,77.290001
11,EAST,308 IPC 1860,04-02-2019 02:23,28.593600,77.325150
12,EAST,"33 DELHI EXCISE ACT, 2010",04-02-2019 00:15,28.605920,77.299470
13,EAST,363/354/343/34 IPC 1860 8 THE PROTECTION OF CH...,03-02-2019 18:00,28.639999,77.290001
14,EAST,"33 DELHI EXCISE ACT, 2009",04-02-2019 01:00,28.616420,77.316960
15,EAST,398/34 IPC 1860,04-02-2019 07:19,28.618860,77.315500
16,EAST,279/337 IPC 1860,03-02-2019 17:40,28.632530,77.298850
17,EAST,188 IPC 1860,03-02-2019 23:36,28.639999,77.290001
18,EAST,"33 DELHI EXCISE ACT, 2009",04-02-2019 01:00,28.639999,77.290001
19,EAST,"40{a) DELHI EXCISE ACT, 2009",04-02-2019 02:54,28.604040,77.379677
20,EAST,"40(a) DELHI EXCISE ACT, 2009",03-02-2019 22:30,28.644690,77.343930
21,EAST,"40(a) DELHI EXCISE ACT, 2009",03-02-2019 22:30,28.740780,77.768900
22,NEW DELHI,"392/397/411 IPC 1860 25/27 ARMS ACT,1959",03-02-2019 23:59,29.099020,77.256409
23,NEW DELHI,"392/397/411 IPC 1860 25/27 ARMS ACT, 1959",03-02-2019 23:58,28.633850,77.200260
24,NORTH,"25/54/59 ARMS ACT, 1959",04-02-2019 07:30,28.676313,77.224976
25,NORTH,"107/151 CODE OF CRIMINAL PROCEDURE, 1973",04-02-2019 00:05,28.676313,77.224976
26,NORTH EAST,392/34 IPC 1860,03-02-2019 19:00,28.696290,77.311810
27,NORTH EAST,"25/54/59 ARMS ACT, 1959",04-02-2019 00:30,28.701500,77.317070
28,NORTH EAST,"33 DELHI EXCISE ACT, 2010",04-02-2019 02:58,28.688430,77.299480
29,NORTH EAST,376/328/506 IPC 1860,03-02-2019 19:30,28.694840,77.348210
...,...,...,...,...,...
349,OUTER DISTRICT,"33 DELHI EXCISE ACT, 2010",09-02-2019 13:18,28.684130,77.095490
350,OUTER DISTRICT,33/38 DELHI EXCISE ACT. 2009,09-02-2019 02:26,28.698200,77.071970
351,OUTER DISTRICT,12/9/55 DELHI PUBLIC GAM8LING ACT. 1955,09-02-2019 11:00,28.689560,77.096480
352,OUTER DISTRICT,12/9/55 DELHI PUBLIC GAMBLING ACT. 1955,08-02-2019 23:44,28.634109,77.216911
353,OUTER DISTRICT,12/9/55 DELHI PUBLIC GAMBLING ACT. 1955,08-02-2019 21:00,28.652910,77.041200
354,OUTER DISTRICT,188/34 IPC 1860,08-02-2019 20:01,28.687410,77.096090
355,OUTER DISTRICT,12/9/55 DELHI PUBLIC GAMBLING ACT. 1955,08-02-2019 20:19,28.634109,77.216911
356,OUTER DISTRICT,40(a) DELHI EXCISE ACT. 2009,08-02-2019 23:00,28.634109,77.216911
357,OUTER DISTRICT,40(a) DELHI EXCISE ACT. 2009,09-02-2019 23:30,28.634109,77.216911
358,OUTER NORTH,25/54/59 ARMS ACT. 1959,08-02-2019 23:45,28.676313,77.224976
359,OUTER NORTH,40(a) DELHI EXCISE ACT. 2009,08-02-2019 21:59,28.694860,77.189160
360,OUTER NORTH,"40(a) DELHI EXCISE ACT, 2009",08-02-2019 21:50,28.676313,77.224976
361,ROHINI,387/506 IPC 1860,08-02-2019 21:11,28.876909,76.911949
362,ROHINI,6 THE PROTECTION OF CHILDREN FROM SEXUAL OFFEN...,08-02-2019 23:50,28.705500,77.281810
363,ROHINI,302 IPC 1860 174A IPC 1860,08-02-2019 21:30,28.700150,77.045700
364,SHAHDAR A,33 DELHI EXCISE ACT. 2009,08-02-2019 22:27,28.689590,77.278023
365,SHAHDAR A,383 IPC 1860,08-02-2019 21:42,28.350273,78.002945
366,SHAHDAR A,40(a) DELHI EXCISE ACT. 2009,08-02-2019 17:10,28.678160,77.408607
367,SHAHDARA,40(a) DELHI EXCISE ACT. 2009,08-02-2019 16:50,28.696930,77.421150
368,SHAHDARA,103 DELHI POLICE ACT 1970,09-02-2019 00:40,29.470289,77.707588
369,SOUTH,379/411 IPC 1860,08-02-2019 16:20,28.706400,77.282610
370,SOUTH,380 IPC1860,09-02-2019 02:19,28.554899,77.191902
371,SOUTH,107/151 CODE OF CRIMINAL PROCEDURE. 1973,09-02-2019 00:00,28.533500,77.199340
372,SOUTH WEST,283 IPC 1860,08-02-2019 21:35,28.648720,77.179340
373,SOUTH WEST,28/112 DELHI POLICE ACT 1978,08-02-2019 18:00,28.609550,77.139671
374,SOUTH- EAST,174A PC 1860,08-02-2019 16:52,22.716221,75.865120
375,SOUTH- EAST,354(A)/354(B)/323/506 IPC 1860,08-02-2019 22:00,28.532620,77.253470
376,SOUTH- EAST,354/354(A)/354(D)/506 IPC 1860,08-02-2019 05:00,28.725838,77.149414
377,SOUTH- EAST,40(a) DELHI EXCISE ACT. 2009,08-02-2019 21:20,28.639999,77.290001
378,WEST,457/380/34 IPC 1860,08-02-2019 22:04,28.696400,77.127098

In [4]:
lis=['District', 'Crime', 'Timestamp']
for c in lis:
    data.drop(c, axis=1, inplace=True)

In [5]:
data

      Latitude  Longitude
0    28.645000  77.245003
1    28.643760  77.231360
2    28.690560  77.041820
3    28.645000  77.245003
4    28.643220  77.217530
5    28.589951  77.040070
6    28.590220  77.070330
7    28.589951  77.040070
8    28.625380  76.966950
9    28.589951  77.040070
10   28.639999  77.290001
11   28.593600  77.325150
12   28.605920  77.299470
13   28.639999  77.290001
14   28.616420  77.316960
15   28.618860  77.315500
16   28.632530  77.298850
17   28.639999  77.290001
18   28.639999  77.290001
19   28.604040  77.379677
20   28.644690  77.343930
21   28.740780  77.768900
22   29.099020  77.256409
23   28.633850  77.200260
24   28.676313  77.224976
25   28.676313  77.224976
26   28.696290  77.311810
27   28.701500  77.317070
28   28.688430  77.299480
29   28.694840  77.348210
..         ...        ...
349  28.684130  77.095490
350  28.698200  77.071970
351  28.689560  77.096480
352  28.634109  77.216911
353  28.652910  77.041200
354  28.687410  77.096090
355  28.634109  77.216911
356  28.634109  77.216911
357  28.634109  77.216911
358  28.676313  77.224976
359  28.694860  77.189160
360  28.676313  77.224976
361  28.876909  76.911949
362  28.705500  77.281810
363  28.700150  77.045700
364  28.689590  77.278023
365  28.350273  78.002945
366  28.678160  77.408607
367  28.696930  77.421150
368  29.470289  77.707588
369  28.706400  77.282610
370  28.554899  77.191902
371  28.533500  77.199340
372  28.648720  77.179340
373  28.609550  77.139671
374  22.716221  75.865120
375  28.532620  77.253470
376  28.725838  77.149414
377  28.639999  77.290001
378  28.696400  77.127098

[379 rows x 2 columns]

In [6]:
xs1=data[data.Latitude< 28.412782]
xs2=data[data.Latitude> 28.88]
xs3=data[data.Longitude< 76.838084]
xs4=data[data.Longitude> 77.323460]
frames = [xs1, xs2, xs3,xs4];
xsFinal = pd.concat(frames)

In [7]:
xsFinal.to_csv("Xfinal.csv")

In [8]:
for i in xsFinal.index:
    if(i in data.index):
        data.drop(i,inplace=True)

In [9]:
data

      Latitude  Longitude
0    28.645000  77.245003
1    28.643760  77.231360
2    28.690560  77.041820
3    28.645000  77.245003
4    28.643220  77.217530
5    28.589951  77.040070
6    28.590220  77.070330
7    28.589951  77.040070
8    28.625380  76.966950
9    28.589951  77.040070
10   28.639999  77.290001
12   28.605920  77.299470
13   28.639999  77.290001
14   28.616420  77.316960
15   28.618860  77.315500
16   28.632530  77.298850
17   28.639999  77.290001
18   28.639999  77.290001
23   28.633850  77.200260
24   28.676313  77.224976
25   28.676313  77.224976
26   28.696290  77.311810
27   28.701500  77.317070
28   28.688430  77.299480
30   28.693600  77.307297
31   28.691180  77.289830
32   28.692230  77.301270
33   28.692470  77.288260
35   28.648940  77.281160
36   28.705350  77.313530
..         ...        ...
344  28.634109  77.216911
345  28.634109  77.216911
346  28.634109  77.216911
347  28.652910  77.041200
348  28.634109  77.216911
349  28.684130  77.095490
350  28.698200  77.071970
351  28.689560  77.096480
352  28.634109  77.216911
353  28.652910  77.041200
354  28.687410  77.096090
355  28.634109  77.216911
356  28.634109  77.216911
357  28.634109  77.216911
358  28.676313  77.224976
359  28.694860  77.189160
360  28.676313  77.224976
361  28.876909  76.911949
362  28.705500  77.281810
363  28.700150  77.045700
364  28.689590  77.278023
369  28.706400  77.282610
370  28.554899  77.191902
371  28.533500  77.199340
372  28.648720  77.179340
373  28.609550  77.139671
375  28.532620  77.253470
376  28.725838  77.149414
377  28.639999  77.290001
378  28.696400  77.127098

[332 rows x 2 columns]

In [10]:
data.reset_index(drop=True,inplace=True)

In [11]:
data['Latitude'].size

332

In [12]:
data=skut.shuffle(data)

In [13]:
data

      Latitude  Longitude
5    28.589951  77.040070
257  28.676313  77.224976
287  28.701250  77.306180
314  28.634109  77.216911
177  28.681150  77.260000
302  28.634109  77.216911
255  28.676313  77.224976
170  28.664100  77.217930
189  28.634109  77.216911
3    28.645000  77.245003
248  28.693600  77.307297
235  28.646150  77.229880
202  28.725838  77.149414
207  28.693600  77.307297
293  28.676313  77.224976
313  28.634109  77.216911
312  28.687410  77.096090
295  28.744300  77.200350
133  28.693600  77.307297
56   28.704480  77.061000
108  28.693600  77.307297
99   28.573650  77.202670
141  28.609550  77.139671
61   28.725838  77.149414
194  28.634109  77.216911
331  28.696400  77.127098
285  28.693600  77.307297
296  28.765840  77.206140
226  28.609550  77.139671
17   28.639999  77.290001
..         ...        ...
125  28.724650  77.088810
91   28.660801  77.100800
323  28.706400  77.282610
232  28.676313  77.224976
279  28.639999  77.290001
200  28.676313  77.224976
324  28.554899  77.191902
237  28.682530  76.914020
59   28.612030  77.314110
85   28.609550  77.139671
95   28.634480  77.087220
121  28.701120  77.080200
6    28.590220  77.070330
50   28.634109  77.216911
4    28.643220  77.217530
103  28.703180  77.256920
49   28.689560  77.096480
48   28.634109  77.216911
26   28.692230  77.301270
19   28.676313  77.224976
93   28.660801  77.100800
147  28.609550  77.139671
187  28.696400  77.127098
298  28.676313  77.224976
186  28.696400  77.127098
309  28.689560  77.096480
197  28.722570  77.145530
199  28.753150  77.150270
18   28.633850  77.200260
10   28.639999  77.290001

[332 rows x 2 columns]

In [14]:
del_index=data[data['Longitude']==76.91194916].index

In [15]:
data.loc[del_index]

      Latitude  Longitude
319  28.876909  76.911949

In [16]:
data=data.drop(del_index)

In [17]:
data.describe()

         Latitude   Longitude
count  331.000000  331.000000
mean    28.656849   77.192487
std      0.053023    0.089428
min     28.462310   76.914020
25%     28.624310   77.131295
50%     28.671590   77.216911
75%     28.693600   77.272705
max     28.767640   77.322070

In [18]:
data['Latitude'].mean()

28.65684934389727

In [19]:
data['Longitude'].mean()

77.19248744782473

In [20]:
kmeans = km(n_clusters=18).fit(data)

In [21]:
prediction=kmeans.predict(data)

In [22]:
centers=kmeans.cluster_centers_

In [23]:
centers

array([[28.61291127, 77.14002955],
       [28.68339039, 77.27562211],
       [28.69894032, 77.08411806],
       [28.72495874, 77.16140472],
       [28.55151174, 77.18850839],
       [28.58465489, 77.04277483],
       [28.67818465, 77.21960872],
       [28.62513985, 77.29582627],
       [28.62540714, 76.96285143],
       [28.67200694, 77.04545291],
       [28.6925364 , 77.30750952],
       [28.68477996, 77.12632023],
       [28.71615393, 77.27239106],
       [28.46642   , 77.16719   ],
       [28.63889265, 77.21945467],
       [28.5281725 , 77.2522675 ],
       [28.7471475 , 77.204085  ],
       [28.61660896, 77.08634468]])

In [24]:
prediction

array([ 5,  6, 10, 14,  1, 14,  6,  6, 14, 14, 10, 14,  3, 10,  6, 14,  2,
       16, 10,  2, 10,  4,  0,  3, 14, 11, 10, 16,  0,  7,  7,  1, 12,  4,
       10,  6,  6, 14,  2,  9,  2,  2,  6,  9,  6,  9,  5,  7, 14,  4,  7,
       14, 12, 14, 14, 12,  8,  6,  9,  0,  5,  4,  1, 12,  1,  5, 10,  2,
        1,  7,  9, 12,  0,  8, 11,  4,  5, 13, 11,  4, 14,  1,  7,  3, 17,
       10,  2,  2, 14,  8, 17,  1,  4, 14, 17, 14,  1,  5,  3,  2,  1,  1,
        0, 17,  0, 10, 12, 14,  1, 10,  5, 14,  0,  3,  2, 10,  1, 14,  7,
       10, 10,  0,  4,  1,  7, 14,  5, 14, 16, 10,  4,  4, 10,  4,  7,  2,
        6,  1,  6, 14, 16,  0,  3, 16,  1,  3,  0,  3,  1,  6,  4, 17, 17,
        6,  2, 12,  1,  1,  6,  0, 14, 12,  1,  0,  1,  7,  0, 14,  2,  9,
       10,  1,  2, 11,  7, 14, 14, 14,  7,  8, 12,  1, 10,  0,  6,  0,  7,
       10,  3,  5,  0,  9,  5, 17, 10, 10,  7,  6,  7,  7,  9,  2,  4,  0,
       10,  7,  7, 11,  8, 11, 10,  5, 15, 11,  7, 14, 10,  2,  9,  7,  7,
        2, 12, 13,  6, 14,  2,  8, 10, 10,  7,  2,  3,  4, 14, 11,  2,  4,
        3,  2,  2, 14,  1, 11, 11,  2,  7,  0,  2,  1,  7,  7, 15,  4,  6,
        9,  6,  6, 16,  6,  6,  3,  1,  3, 14, 12, 10,  7,  6,  0,  0,  2,
       16,  2, 10,  6, 10, 10,  0,  4, 15, 11, 14, 16,  0, 11, 17, 14,  2,
       12,  5, 12,  1, 14,  6,  3,  4,  7,  3, 10, 15,  2, 11, 12,  6,  7,
        6,  4,  8,  7,  0, 17,  2,  5, 14, 14, 12,  2, 14, 10,  6, 11,  0,
       11,  6, 11,  2,  3,  3, 14,  7])

In [25]:
center_count=[]

In [26]:
for i in range(18):
    center_count.append(list(prediction).count(i))

In [27]:
center_count

[24, 26, 31, 17, 19, 13, 29, 30, 7, 10, 32, 16, 15, 2, 39, 4, 8, 9]

In [28]:
max_value=max(center_count)

In [29]:
min_value=min(center_count)

In [30]:
avg_value=(max_value+min_value)/3

In [31]:
range1=int(min_value+avg_value)

In [32]:
range1

15

In [33]:
range2=int(max_value-avg_value)

In [34]:
range2

25

In [35]:
#color_list=['cornflowerblue', 'red', 'green', 'yellow', 'brown', 'black', 'aqua', 'darkgray', 'gold', 'ghostwhite', 'hotpink', 'mistyrose', 'orange', 'purple', 'silver', 'lime', 'salmon', 'steelblue']

In [36]:
color_list=['red', 'yellow', 'green']

In [37]:
g = geocoder.bing("Delhi, India", key='Av3MzjFGfdPT198iOOm1o5cUm9SohZKyKX_4ioh0IPW8xj4Uut_HOFxz2hbOAKyV')

In [38]:
gmap1 = gm.GoogleMapPlotter(g.lat, g.lng, 12)
gmap1.scatter(list(data['Latitude']), list(data['Longitude']), '# FF0000', size = 100, marker = False)

In [39]:
j=0
for i in centers:
    if center_count[j] in range(min_value, range1):
        gmap1.marker(i[0], i[1], color_list[2])
    elif center_count[j] in range(range2, max_value+1):
        gmap1.marker(i[0], i[1], color_list[0])
    else:
        gmap1.marker(i[0], i[1], color_list[1])
    j=j+1

In [40]:
gmap1.draw("cluster.html")

In [41]:
g.bbox

{'northeast': [28.71649932861328, 77.32664489746094],
 'southwest': [28.50888442993164, 77.07470703125]}

In [42]:
gmap2 = gm.GoogleMapPlotter(g.lat, g.lng, 12)
gmap2.scatter(list(data['Latitude']), list(data['Longitude']), '# FF0000', size = 100, marker = False)

In [43]:
gmap2.marker(28.715712, 77.323460, 'cornflowerblue')
gmap2.marker(28.412782, 77.200218, 'red')
gmap2.marker(28.88, 77.07470703125, 'green')
gmap2.marker(28.577869, 76.838084, 'yellow')

In [44]:
gmap2.draw("abcdef.html")

In [53]:
import pickle

In [54]:
filename="model.sav"
pickle.dump(kmeans, open(filename, 'wb'))