In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn.cluster import KMeans as km
import sklearn.utils as skut
import gmplot as gm
import geocoder

In [2]:
data=pd.read_csv("Final.csv")

In [3]:
data

,District,Crime,Timestamp,Latitude,Longitude
0,CENTRAL,356/379/411 IPC 1860,03-02-2019 22:20,28.645000,77.245003
1,CENTRAL,323/341/506 IPC 1860,04-02-2019 03:00,28.643760,77.231360
2,CENTRAL,283/290 IPC 1860,03-02-2019 21:00,28.690560,77.041820
3,CENTRAL,93/97 DELHI POLICE ACT 1978,03-02-2019 22:00,28.645000,77.245003
4,CENTRAL,93/97 DELHI POLICE ACT 1978,03-02-2019 22:00,28.643220,77.217530
5,DWARKA,"40(b) DELHI EXCISE ACT, 2009",03-02-2019 20:38,28.589951,77.040070
6,DWARKA,93/97 DELHI POLICE ACT 1978,03-02-2019 23:00,28.590220,77.070330
7,DWARKA,"40(b) DELHI EXCISE ACT, 2009",03-02-2019 20:24,28.589951,77.040070
8,DWARKA,"40(b) DELHI EXCISE ACT, 2009",03-02-2019 20:38,28.625380,76.966950
9,DWARKA,"40(b) DELHI EXCISE ACT, 2009",03-02-2019 20:24,28.589951,77.040070
10,EAST,"33 DELHI EXCISE ACT, 2010",03-02-2019 21:51,28.639999,77.290001
11,EAST,308 IPC 1860,04-02-2019 02:23,28.593600,77.325150
12,EAST,"33 DELHI EXCISE ACT, 2010",04-02-2019 00:15,28.605920,77.299470
13,EAST,363/354/343/34 IPC 1860 8 THE PROTECTION OF CH...,03-02-2019 18:00,28.639999,77.290001
14,EAST,"33 DELHI EXCISE ACT, 2009",04-02-2019 01:00,28.616420,77.316960
15,EAST,398/34 IPC 1860,04-02-2019 07:19,28.618860,77.315500
16,EAST,279/337 IPC 1860,03-02-2019 17:40,28.632530,77.298850
17,EAST,188 IPC 1860,03-02-2019 23:36,28.639999,77.290001
18,EAST,"33 DELHI EXCISE ACT, 2009",04-02-2019 01:00,28.639999,77.290001
19,EAST,"40{a) DELHI EXCISE ACT, 2009",04-02-2019 02:54,28.604040,77.379677
20,EAST,"40(a) DELHI EXCISE ACT, 2009",03-02-2019 22:30,28.644690,77.343930
21,EAST,"40(a) DELHI EXCISE ACT, 2009",03-02-2019 22:30,28.740780,77.768900
22,NEW DELHI,"392/397/411 IPC 1860 25/27 ARMS ACT,1959",03-02-2019 23:59,29.099020,77.256409
23,NEW DELHI,"392/397/411 IPC 1860 25/27 ARMS ACT, 1959",03-02-2019 23:58,28.633850,77.200260
24,NORTH,"25/54/59 ARMS ACT, 1959",04-02-2019 07:30,28.676313,77.224976
25,NORTH,"107/151 CODE OF CRIMINAL PROCEDURE, 1973",04-02-2019 00:05,28.676313,77.224976
26,NORTH EAST,392/34 IPC 1860,03-02-2019 19:00,28.696290,77.311810
27,NORTH EAST,"25/54/59 ARMS ACT, 1959",04-02-2019 00:30,28.701500,77.317070
28,NORTH EAST,"33 DELHI EXCISE ACT, 2010",04-02-2019 02:58,28.688430,77.299480
29,NORTH EAST,376/328/506 IPC 1860,03-02-2019 19:30,28.694840,77.348210
...,...,...,...,...,...
349,OUTER DISTRICT,"33 DELHI EXCISE ACT, 2010",09-02-2019 13:18,28.684130,77.095490
350,OUTER DISTRICT,33/38 DELHI EXCISE ACT. 2009,09-02-2019 02:26,28.698200,77.071970
351,OUTER DISTRICT,12/9/55 DELHI PUBLIC GAM8LING ACT. 1955,09-02-2019 11:00,28.689560,77.096480
352,OUTER DISTRICT,12/9/55 DELHI PUBLIC GAMBLING ACT. 1955,08-02-2019 23:44,28.634109,77.216911
353,OUTER DISTRICT,12/9/55 DELHI PUBLIC GAMBLING ACT. 1955,08-02-2019 21:00,28.652910,77.041200
354,OUTER DISTRICT,188/34 IPC 1860,08-02-2019 20:01,28.687410,77.096090
355,OUTER DISTRICT,12/9/55 DELHI PUBLIC GAMBLING ACT. 1955,08-02-2019 20:19,28.634109,77.216911
356,OUTER DISTRICT,40(a) DELHI EXCISE ACT. 2009,08-02-2019 23:00,28.634109,77.216911
357,OUTER DISTRICT,40(a) DELHI EXCISE ACT. 2009,09-02-2019 23:30,28.634109,77.216911
358,OUTER NORTH,25/54/59 ARMS ACT. 1959,08-02-2019 23:45,28.676313,77.224976
359,OUTER NORTH,40(a) DELHI EXCISE ACT. 2009,08-02-2019 21:59,28.694860,77.189160
360,OUTER NORTH,"40(a) DELHI EXCISE ACT, 2009",08-02-2019 21:50,28.676313,77.224976
361,ROHINI,387/506 IPC 1860,08-02-2019 21:11,28.876909,76.911949
362,ROHINI,6 THE PROTECTION OF CHILDREN FROM SEXUAL OFFEN...,08-02-2019 23:50,28.705500,77.281810
363,ROHINI,302 IPC 1860 174A IPC 1860,08-02-2019 21:30,28.700150,77.045700
364,SHAHDAR A,33 DELHI EXCISE ACT. 2009,08-02-2019 22:27,28.689590,77.278023
365,SHAHDAR A,383 IPC 1860,08-02-2019 21:42,28.350273,78.002945
366,SHAHDAR A,40(a) DELHI EXCISE ACT. 2009,08-02-2019 17:10,28.678160,77.408607
367,SHAHDARA,40(a) DELHI EXCISE ACT. 2009,08-02-2019 16:50,28.696930,77.421150
368,SHAHDARA,103 DELHI POLICE ACT 1970,09-02-2019 00:40,29.470289,77.707588
369,SOUTH,379/411 IPC 1860,08-02-2019 16:20,28.706400,77.282610
370,SOUTH,380 IPC1860,09-02-2019 02:19,28.554899,77.191902
371,SOUTH,107/151 CODE OF CRIMINAL PROCEDURE. 1973,09-02-2019 00:00,28.533500,77.199340
372,SOUTH WEST,283 IPC 1860,08-02-2019 21:35,28.648720,77.179340
373,SOUTH WEST,28/112 DELHI POLICE ACT 1978,08-02-2019 18:00,28.609550,77.139671
374,SOUTH- EAST,174A PC 1860,08-02-2019 16:52,22.716221,75.865120
375,SOUTH- EAST,354(A)/354(B)/323/506 IPC 1860,08-02-2019 22:00,28.532620,77.253470
376,SOUTH- EAST,354/354(A)/354(D)/506 IPC 1860,08-02-2019 05:00,28.725838,77.149414
377,SOUTH- EAST,40(a) DELHI EXCISE ACT. 2009,08-02-2019 21:20,28.639999,77.290001
378,WEST,457/380/34 IPC 1860,08-02-2019 22:04,28.696400,77.127098

In [4]:
lis=['District', 'Crime', 'Timestamp']
for c in lis:
    data.drop(c, axis=1, inplace=True)

In [5]:
data

      Latitude  Longitude
0    28.645000  77.245003
1    28.643760  77.231360
2    28.690560  77.041820
3    28.645000  77.245003
4    28.643220  77.217530
5    28.589951  77.040070
6    28.590220  77.070330
7    28.589951  77.040070
8    28.625380  76.966950
9    28.589951  77.040070
10   28.639999  77.290001
11   28.593600  77.325150
12   28.605920  77.299470
13   28.639999  77.290001
14   28.616420  77.316960
15   28.618860  77.315500
16   28.632530  77.298850
17   28.639999  77.290001
18   28.639999  77.290001
19   28.604040  77.379677
20   28.644690  77.343930
21   28.740780  77.768900
22   29.099020  77.256409
23   28.633850  77.200260
24   28.676313  77.224976
25   28.676313  77.224976
26   28.696290  77.311810
27   28.701500  77.317070
28   28.688430  77.299480
29   28.694840  77.348210
..         ...        ...
349  28.684130  77.095490
350  28.698200  77.071970
351  28.689560  77.096480
352  28.634109  77.216911
353  28.652910  77.041200
354  28.687410  77.096090
355  28.634109  77.216911
356  28.634109  77.216911
357  28.634109  77.216911
358  28.676313  77.224976
359  28.694860  77.189160
360  28.676313  77.224976
361  28.876909  76.911949
362  28.705500  77.281810
363  28.700150  77.045700
364  28.689590  77.278023
365  28.350273  78.002945
366  28.678160  77.408607
367  28.696930  77.421150
368  29.470289  77.707588
369  28.706400  77.282610
370  28.554899  77.191902
371  28.533500  77.199340
372  28.648720  77.179340
373  28.609550  77.139671
374  22.716221  75.865120
375  28.532620  77.253470
376  28.725838  77.149414
377  28.639999  77.290001
378  28.696400  77.127098

[379 rows x 2 columns]

In [6]:
d_len=len(data.index)

In [7]:
rownum=[]

In [8]:
def remove_outliers():
    for i in range(d_len):
        if data['Latitude'][i] < 28.412782:
            rownum.append(i)#data['Latitude'][i] = 28.412782
        elif data['Latitude'][i] > 28.88:
            rownum.append(i)#data['Latitude'][i] = 28.88
        if data['Longitude'][i] < 76.838084:
            rownum.append(i)#data['Longitude'][i] = 76.838084
        elif data['Longitude'][i] > 77.323460:
            rownum.append(i)#data['Longitude'][i] = 77.323460

In [9]:
remove_outliers()

In [10]:
#data=data.drop(new_data.index, axis=0)

In [11]:
rownum

[11,
 19,
 20,
 21,
 22,
 29,
 34,
 34,
 42,
 42,
 46,
 46,
 50,
 66,
 66,
 70,
 70,
 73,
 73,
 82,
 89,
 89,
 90,
 90,
 108,
 116,
 116,
 145,
 145,
 146,
 146,
 147,
 154,
 156,
 156,
 158,
 158,
 159,
 186,
 186,
 191,
 191,
 211,
 214,
 214,
 232,
 232,
 243,
 251,
 254,
 254,
 256,
 256,
 258,
 272,
 272,
 287,
 287,
 291,
 300,
 308,
 308,
 316,
 316,
 320,
 365,
 365,
 366,
 367,
 368,
 368,
 374,
 374]

In [12]:
rownum=list(dict.fromkeys(rownum))

In [13]:
rownum

[11,
 19,
 20,
 21,
 22,
 29,
 34,
 42,
 46,
 50,
 66,
 70,
 73,
 82,
 89,
 90,
 108,
 116,
 145,
 146,
 147,
 154,
 156,
 158,
 159,
 186,
 191,
 211,
 214,
 232,
 243,
 251,
 254,
 256,
 258,
 272,
 287,
 291,
 300,
 308,
 316,
 320,
 365,
 366,
 367,
 368,
 374]

In [14]:
len(rownum)

47

In [15]:
data

      Latitude  Longitude
0    28.645000  77.245003
1    28.643760  77.231360
2    28.690560  77.041820
3    28.645000  77.245003
4    28.643220  77.217530
5    28.589951  77.040070
6    28.590220  77.070330
7    28.589951  77.040070
8    28.625380  76.966950
9    28.589951  77.040070
10   28.639999  77.290001
11   28.593600  77.325150
12   28.605920  77.299470
13   28.639999  77.290001
14   28.616420  77.316960
15   28.618860  77.315500
16   28.632530  77.298850
17   28.639999  77.290001
18   28.639999  77.290001
19   28.604040  77.379677
20   28.644690  77.343930
21   28.740780  77.768900
22   29.099020  77.256409
23   28.633850  77.200260
24   28.676313  77.224976
25   28.676313  77.224976
26   28.696290  77.311810
27   28.701500  77.317070
28   28.688430  77.299480
29   28.694840  77.348210
..         ...        ...
349  28.684130  77.095490
350  28.698200  77.071970
351  28.689560  77.096480
352  28.634109  77.216911
353  28.652910  77.041200
354  28.687410  77.096090
355  28.634109  77.216911
356  28.634109  77.216911
357  28.634109  77.216911
358  28.676313  77.224976
359  28.694860  77.189160
360  28.676313  77.224976
361  28.876909  76.911949
362  28.705500  77.281810
363  28.700150  77.045700
364  28.689590  77.278023
365  28.350273  78.002945
366  28.678160  77.408607
367  28.696930  77.421150
368  29.470289  77.707588
369  28.706400  77.282610
370  28.554899  77.191902
371  28.533500  77.199340
372  28.648720  77.179340
373  28.609550  77.139671
374  22.716221  75.865120
375  28.532620  77.253470
376  28.725838  77.149414
377  28.639999  77.290001
378  28.696400  77.127098

[379 rows x 2 columns]

In [16]:
row_len=len(rownum)

In [17]:
for i in range(row_len):
    data.drop(rownum[i], inplace=True)

In [18]:
len(data.index)

332

In [19]:
data

      Latitude  Longitude
0    28.645000  77.245003
1    28.643760  77.231360
2    28.690560  77.041820
3    28.645000  77.245003
4    28.643220  77.217530
5    28.589951  77.040070
6    28.590220  77.070330
7    28.589951  77.040070
8    28.625380  76.966950
9    28.589951  77.040070
10   28.639999  77.290001
12   28.605920  77.299470
13   28.639999  77.290001
14   28.616420  77.316960
15   28.618860  77.315500
16   28.632530  77.298850
17   28.639999  77.290001
18   28.639999  77.290001
23   28.633850  77.200260
24   28.676313  77.224976
25   28.676313  77.224976
26   28.696290  77.311810
27   28.701500  77.317070
28   28.688430  77.299480
30   28.693600  77.307297
31   28.691180  77.289830
32   28.692230  77.301270
33   28.692470  77.288260
35   28.648940  77.281160
36   28.705350  77.313530
..         ...        ...
344  28.634109  77.216911
345  28.634109  77.216911
346  28.634109  77.216911
347  28.652910  77.041200
348  28.634109  77.216911
349  28.684130  77.095490
350  28.698200  77.071970
351  28.689560  77.096480
352  28.634109  77.216911
353  28.652910  77.041200
354  28.687410  77.096090
355  28.634109  77.216911
356  28.634109  77.216911
357  28.634109  77.216911
358  28.676313  77.224976
359  28.694860  77.189160
360  28.676313  77.224976
361  28.876909  76.911949
362  28.705500  77.281810
363  28.700150  77.045700
364  28.689590  77.278023
369  28.706400  77.282610
370  28.554899  77.191902
371  28.533500  77.199340
372  28.648720  77.179340
373  28.609550  77.139671
375  28.532620  77.253470
376  28.725838  77.149414
377  28.639999  77.290001
378  28.696400  77.127098

[332 rows x 2 columns]

In [20]:
data['Latitude'].size

332

In [21]:
data=skut.shuffle(data)

In [22]:
data

      Latitude  Longitude
288  28.696400  77.127098
109  28.616930  77.081360
130  28.724110  77.166820
51   28.707540  77.177360
286  28.695860  77.270130
48   28.691280  77.186550
339  28.708300  77.177800
81   28.670660  77.282390
151  28.735360  77.113550
350  28.698200  77.071970
352  28.634109  77.216911
149  28.690810  77.127050
208  28.693600  77.307297
229  28.676313  77.224976
334  28.676313  77.224976
303  28.724570  77.216690
54   28.719670  77.170860
358  28.676313  77.224976
0    28.645000  77.245003
198  28.687700  77.261250
45   28.696400  77.127098
124  28.693600  77.307297
209  28.693600  77.307297
362  28.705500  77.281810
98   28.609550  77.139671
139  28.701120  77.080200
317  28.589951  77.040070
63   28.676313  77.224976
94   28.657450  77.207640
30   28.693600  77.307297
..         ...        ...
271  28.645590  77.189510
338  28.765840  77.206140
330  28.693600  77.307297
5    28.589951  77.040070
80   28.692930  77.127100
17   28.639999  77.290001
28   28.688430  77.299480
363  28.700150  77.045700
273  28.682530  76.914020
299  28.706640  77.267170
175  28.699680  77.100860
313  28.630400  77.302850
190  28.725838  77.149414
242  28.677270  77.301860
328  28.693600  77.307297
25   28.676313  77.224976
188  28.625930  77.299550
141  28.663920  77.092200
227  28.621981  77.055252
86   28.620130  77.236500
346  28.634109  77.216911
221  28.686030  77.070070
321  28.639999  77.290001
289  28.726870  77.164210
182  28.602900  77.049040
185  28.625540  77.308470
92   28.589170  77.254173
118  28.676313  77.224976
36   28.705350  77.313530
71   28.612030  77.314110

[332 rows x 2 columns]

In [23]:
data['Latitude'].mean()

28.65751217496985

In [24]:
data['Longitude'].mean()

77.19164245298191

In [25]:
kmeans = km(n_clusters=18).fit(data)

In [26]:
prediction=kmeans.predict(data)

In [27]:
prediction

array([ 2,  1, 11, 11,  0, 13, 11,  0,  2, 16, 15,  2, 12, 13, 13,  8, 11,
       13,  6,  0,  2, 12, 12,  0,  7, 16,  1, 13, 15, 12, 13, 13,  4, 13,
        7, 14, 11, 12,  4,  7, 15, 13,  4,  6, 10, 13,  0, 14,  1, 12,  3,
        2, 13,  4,  2, 12, 15, 12,  8, 12,  6,  8,  1,  1, 13, 15,  4, 16,
        7, 12, 16,  2, 15,  7,  3,  6,  3, 13,  7, 12, 13,  1,  8, 10, 15,
       12,  6,  7, 17, 12,  0, 16,  1, 16,  0,  6,  0,  4, 15, 16, 15,  0,
        1,  0, 15,  0, 12, 11,  0, 15, 15, 12, 16, 11,  7,  0, 13,  2, 16,
        0,  1,  0,  0,  3,  0,  2,  4,  5, 15,  3, 13, 12, 12,  5,  8,  4,
       12,  3,  0,  5,  7,  7, 16, 15,  5,  0,  5,  6, 12,  4,  6,  4, 11,
       13, 16, 12, 14,  3,  3, 11, 15,  2,  0, 10,  6, 12,  7, 11,  1, 13,
        3,  5,  2,  0,  7, 16, 11, 12,  7,  3,  7,  0, 12,  7,  4, 13,  3,
        1, 15,  8, 12,  8, 12,  4, 17, 15,  6, 16, 16, 11, 13,  4,  3, 11,
        7,  4, 16,  7, 16,  1, 16, 12,  4, 15,  0,  2,  0,  7, 16,  5,  7,
       13,  4,  4, 13, 14,  0, 10, 11, 16, 11, 15, 14, 16, 16,  8,  4,  7,
       12,  5, 16,  8, 16,  1,  3, 10, 15,  7,  1,  7, 12, 10, 11,  3,  4,
        0,  7, 17, 11, 16,  7,  1, 15,  4,  0, 15,  3, 11, 15, 16,  0, 13,
        8, 16,  8,  0, 10, 15, 13, 17, 13,  8,  7,  7, 16,  5,  4,  4,  2,
       15, 13,  9, 16, 14,  1, 11,  4, 16, 13,  0, 15,  2, 15, 11, 12,  1,
        2,  4, 12,  5, 10,  8, 16,  4, 11, 12, 12, 13,  4, 16,  1,  6, 15,
       16,  4, 11,  1,  4,  6, 13, 12,  4])

In [28]:
centers=kmeans.cluster_centers_

In [29]:
centers

array([[28.68793901, 77.27625049],
       [28.5968229 , 77.05856362],
       [28.69134917, 77.12887164],
       [28.55921087, 77.19414196],
       [28.62638017, 77.29726258],
       [28.67200694, 77.04545291],
       [28.63887447, 77.24164438],
       [28.61394656, 77.13779151],
       [28.72149145, 77.2552943 ],
       [28.87690926, 76.91194916],
       [28.61693364, 76.96731952],
       [28.73296539, 77.16937956],
       [28.69182742, 77.30715802],
       [28.67818465, 77.21960872],
       [28.5039    , 77.16731833],
       [28.63712465, 77.21118474],
       [28.6954185 , 77.08424091],
       [28.5281725 , 77.2522675 ]])

In [30]:
color_list=['cornflowerblue', 'red', 'green', 'yellow', 'brown', 'black', 'aqua', 'darkgray', 'gold', 'ghostwhite', 'hotpink', 'mistyrose', 'orange', 'purple', 'silver', 'lime', 'salmon', 'steelblue']

In [31]:
g = geocoder.bing("Delhi, India", key='Av3MzjFGfdPT198iOOm1o5cUm9SohZKyKX_4ioh0IPW8xj4Uut_HOFxz2hbOAKyV')

In [32]:
gmap1 = gm.GoogleMapPlotter(g.lat, g.lng, 12)

In [33]:
j=0
for i in centers:
    gmap1.marker(i[0], i[1], color_list[j])
    j=j+1

In [34]:
'''for i in range(len(data.index)):
    gmap1.scatter(list(data['Latitude'][i]), list(data['Longitude'][i]), color_list[prediction[i]], size=100, marker=False)'''

"for i in range(len(data.index)):\n    gmap1.scatter(list(data['Latitude'][i]), list(data['Longitude'][i]), color_list[prediction[i]], size=100, marker=False)"

In [35]:
gmap1.draw("mycluster.html")

In [36]:
g.bbox

{'northeast': [28.71649932861328, 77.32664489746094],
 'southwest': [28.50888442993164, 77.07470703125]}

In [37]:
gmap2 = gm.GoogleMapPlotter(g.lat, g.lng, 12)

In [38]:
gmap2.marker(28.715712, 77.323460, 'cornflowerblue')
gmap2.marker(28.412782, 77.200218, 'red')
gmap2.marker(28.88, 77.07470703125, 'green')
gmap2.marker(28.577869, 76.838084, 'yellow')

In [39]:
gmap2.draw("abcdef.html")